# Change these first
owner: alter095
repo:  monitor_upptime

sites:
  - name: massmist
    url: https://massmist.net/
  - name: dp-massmist -Dolphin-
    url: https://dp.massmist.net/

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: monupp.massmist.net
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /monitor_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: massmiStatus with Upptime
  introTitle: "massmiStatusでは オープンソースソフトウェアの **Upptime** を用いて死活チェックを行っています。"
  introMessage: massmistにて運用しているサービスの状況が、こちらで表示されます。不調な際は随時レポートが作成され、管理人に通知が飛びます。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Twitter
      href: https://twitter.com/alter095
i18n:
  activeIncidents: 問題が起きています
  allSystemsOperational: 全システム動作中
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
